/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Select the Product you wish to target
 */
#undef  CONFIG_DEFAULTS_RALINK_RT2880
#define CONFIG_DEFAULTS_RALINK_RT3052 1
#define CONFIG_DEFSETTING_2M16M 1
#undef  CONFIG_DEFSETTING_4M16M
#undef  CONFIG_DEFSETTING_4M32M

/*
 * Kernel/Library/Defaults Selection
 */
#define CONFIG_DEFAULTS_KERNEL_2_6_21 1
#define CONFIG_CROSS_COMPILER_PATH "/opt/buildroot-gcc342/bin"
#undef  CONFIG_DEFAULTS_OVERRIDE
#undef  CONFIG_DEFAULTS_KERNEL
#define CONFIG_DEFAULTS_VENDOR 1
#undef  CONFIG_DEFAULTS_BUSYBOX
#undef  CONFIG_DEFAULTS_UCLIBC
#undef  CONFIG_DEFAULTS_UCLIBC_PLUS_PLUS
#undef  CONFIG_DEFAULTS_VENDOR_UPDATE
